version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: c_elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /root/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - local-net
  kibana:
    image: kibana:8.6.2
    container_name: c_kibana
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_URL=http://c_elasticsearch:9200
      - XPACK_MONITORING_ENABLED=true
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - local-net
networks:
  local-net:
    external: true



